### PR TITLE
Update non-summary partitioning

### PR DESCRIPTION
**Pull request by giancarloaf**
Add logging for non-summary partitioning failures

Validation job
https://console.cloud.google.com/dataflow/jobs/us-west1/2022-07-01_15_50_18-12666859198052476544?project=httparchive

### CODE REVIEW

**Comment by rviscomi** [comment]
You can't win with the linter

https://github.com/HTTPArchive/data-pipeline/pull/91#issuecomment-1171931569

**Review by rviscomi — APPROVED** [review]

**Comment by rviscomi** [comment]
I can force merge when you're ready if the linter is blocking you

**Comment by giancarloaf** [comment]
> I can force merge when you're ready if the linter is blocking you

yes please, ready!

**Comment by tunetheweb** [comment]
> You can't win with the linter

You can! Fixed in #108

**Pull request merged**
